config/routes.rb
Rails.application.routes.draw do

  root "stores#index"
  resources :stores, only: [:index, :show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    respond_to do |format|
      format.html do
      end
      format.js do
        json = RestClient.get "http://api.gnavi.co.jp/RestSearchAPI/20150630/",
          {
            params: {
              keyid: ENV['GNAVI_API_KEY'],
              format: 'json',
              offset_page: params[:stores][:page],
              input_coordinates_mode: 1,
              latitude: params[:stores][:latitude],
              longitude: params[:stores][:longitude],
              range: params[:stores][:range],
              lunch: 1
            }
          }
        @shops = JSON.parse json
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunch5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/stores/_index.html.erb
<% @shops['rest'].present? && @shops['rest'].each do |shop| %>
<% image = shop['image_url']['shop_image1'] %>
<div class="main">
  <section>
    <div class="main-image">
      <% if  image.empty? %>
        <img src="/assets/no_image.png" height="270" width="270" style="border: solid gray 1px;" data-toggle="modal" data-target="#<%= shop['id'] %>">
      <% else %>
        <img src= <%= image %> width="270" height="270" data-toggle="modal" data-target="#<%= shop['id'] %>">
      <% end %>
    </div>
    <div class="modal fade" id="<%= shop['id'] %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <% if  image.empty? %>
              <img src="/assets/no_image.png" height="270" width="270" style="border: solid gray 1px;">
            <% else %>
              <img src= <%= image %> width="270" height="270">
            <% end %>
            <h2>店舗名:<%= shop['name'] %></h2>
            <p><b>住所</b>:<%= shop['address'] %></p>
            <p><b>TEL</b>:<%= shop['tel'] %></p>
            <% if shop['opentime'].empty? %>
              <p><b>営業時間</b>:--</p>
            <% else %>
              <p><b>営業時間</b>:<%= shop['opentime'] %></p>
            <% end %>
            <% if shop['coupon_url']['mobile'].empty? %>
              <p><b>クーポン</b>:--</p>
            <% else %>
              <p><b>クーポン</b>:<%= link_to "#{shop['coupon_url']['mobile']}","#{shop['coupon_url']['mobile']}" %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="main-text">
      <h2>店舗名:<%= shop['name'] %></h2>
      <% if shop['lunch'].empty? %>
        <p><b>ランチ営業</b>:なし</p>
        <p><b>ランチ平均予算</b>:--円</p>
      <% else %>
        <p><b>ランチ営業</b>:あり</p>
        <p><b>ランチ平均予算</b>:<%= shop['lunch'] %>円</p>
      <% end %>
      <% if shop['lunch'].empty? %>
        <p><b>徒歩</b>:--分</p>
      <% else %>
        <p><b>徒歩</b>:<%= shop['access']['walk'] %>分</p>
      <% end %>
      <p><b>住所</b>:<%= shop['address'] %></p>
   </div>
  </section>
</div>

<% end %>

app/views/stores/index.html.erb
  <div class="header">
      <div class="header-left">
        Lunch5
      </div>
      <div class="header-right">
        <div id="header-right-select">
          <select id="range" class="form-control" >
            <option value="1">300m</option>
            <option value="2">500m</option>
            <option value="3">1000m</option>
            <option value="4">2000m</option>
            <option value="5">3000m</option>
          </select>
          <input type="hidden" name="range" id="range_hidden">
        </div>
        <%= submit_tag '検索', id: 'search', class: "btn primary-btn header-right-search" %>
      </div>
  </div>

  <div id="shops">
    <div class="centering">読み込み中です。しばらくお待ち下さい。</div>
  </div>

<div class="more-button">
  <%= button_tag 'もっと読む', id: 'more-read', class: "btn center-block primary-btn" %>
</div>
  <%= form_tag stores_path, id: 'search-form', method: :get, remote: true do %>
    <%= hidden_field_tag 'stores[latitude]' %>
    <%= hidden_field_tag 'stores[longitude]' %>
    <%= hidden_field_tag 'stores[page]', 0 %>
    <%= hidden_field_tag 'stores[range]' %>
  <% end %>

app/views/stores/index.js.erb
var _html = (function () {/*
  <%= render 'index' %>
*/}).toString().replace(/(\n)/g, '').split('*')[1];

$("#shops").append(_html);

if ("<%= @shops['rest'] %>" === "") {
  $("#more-read").hide();
} else {
  $("#more-read").css('display', 'block')
};